### ISSUE TITLE
On Login Finished getting called multiple times

### ISSUE THREAD

**Issue by WiechersV** [facebook/react-native-fbsdk#133]
Hey guys!

Just started using FBSdk for react native. I am currently trying to implement FB Login and everything is working fine, except for one little detail.

```
<LoginButton
          readPermissions={["public_profile, email"]}
          onLoginFinished={
            (error, result) => {
              console.log("Logged in!");
              AccessToken.getCurrentAccessToken()
              .then((token) => {
                this._serverLogin(token);
              }, (error) => {
                console.log(error);
              });
            }
          }
          onLogoutFinished={() => alert("logout.")}/>
```
![captura de tela 2016-04-22 as 23 21 00](https://cloud.githubusercontent.com/assets/4604886/14758753/c8e32936-08e0-11e6-94b2-16fa55132899.png)

`onLoginFinished` is being called exactly 9 times, every time I login via facebook. I followed the instructions, but don't know why is this happening.
Is this happening with someone else? Could this be a bug on the rnfbsdk or I'm doing something wrong?

Thanks in advance ;)

**Comment by xelent** [comment]
I can confirm that mine is also being called 9 times.

**Comment by prtkkmrsngh** [comment]
Any fix for this?

**Comment by dattran92** [comment]
the same to me. Any fixed?

**Comment by charpeni** [comment]
cc @dzhuowen

**Comment by SrihariThalla** [comment]
I get this, 9 times, at my end too!

**Comment by dzhuowen** [comment]
Sorry for the error, I'll fix this issue in the next release

**Comment by dzhuowen** [comment]
Closing b/c this bug is fixed in 0.2.0.

**Comment by gannetson** [comment]
I still have this in 0.2.0. What is the commit that fixes it?

**Comment by osungjin** [comment]
@gannetson I use 0.2.1. This bug fixed it.

**Comment by gannetson** [comment]
Yeah, building the sdk again instead of just reloading JS did the trick. Sorry for the noob-ishness :-P

**Comment by jonnyberanek** [comment]
I'm seeing a similar situation to this still. `onLoginFinished` does not trigger at all after a JS reload.

Is there any chance this will be fixed? While this doesn't affect production, it definitely set me and my team back a few hours on a wild bug chase and I'm sure it has for many others who have encountered the issue, as well.
