### ISSUE TITLE
No known class method for selector 'objectForJSONString:error:'

### ISSUE THREAD

**Issue by punjabistream** [facebook/react-native-fbsdk#539]
NSDictionary<id, id> *existingState = [FBSDKBasicUtility objectForJSONString:params[FBSDKLoginManagerLoggingClientStateKey] error:NULL];

RN - 0.59.9
react-native-fbsdk - 0.8.0

**Comment by Riadh-Mkhinini** [comment]
same error :(

**Comment by steinarsa** [comment]
Got the same error

**Comment by Alop241** [comment]
I´m having the same error on `FBSDKLoginCompletion.m` of `FBSDKLoginKit` after updating FBSDK to version 5.0 with `react-native-fbsdk: 0.8.0`

**Comment by hakanozcn** [comment]
same error

**Comment by felipedovale** [comment]
same error

**Comment by javi10823** [comment]
Same error here, any solution?

**Comment by maharleeeka** [comment]
is this fixed with the new version in rn fbsdk?

**Comment by scaralfred** [comment]
Any solution? I also tried version '0.10.0' but it is still throwing the same issue.

**Comment by rodrigopk** [comment]
I ended up fixing the version fo the `FacebookSDK/LoginKit` pod to `5.0` in order to make the build work after updating the library to `0.10.0`.

**Comment by bizplannerMarcos** [comment]
@rodrigopk could you show me your pod file? Thank you

**Comment by scaralfred** [comment]
@rodrigopk hope you can share your pod file. Thanks in advance

**Comment by cereme** [comment]
```
platform :ios, '9.0'

target 'Myapp' do
  #use_frameworks!
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FacebookSDK'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit', '~> 5.0'
  target 'MyappTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

Simply making FBSDKLoginKit to version 5.0 did it.
Thanks to @rodrigopk

**Comment by scaralfred** [comment]
Unfortunately the above solution didn't work for me. If I use that pod file setup, I still get the same error.
I'm trying to setup the pod file using different versions of those libraries, and I sometimes get ride of that error, but another one shows up => Missing... 'FBSDKCoreKit/FBSDKAppEvents.h'

**Comment by vladborovtsov** [comment]
@scaralfred adding FBSDKShareKit and FBSDKLoginKit solved my issue (but with 5.15.1).
